name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          # Пути теперь относительно корня репозитория
          cache-dependency-path: |
            package-lock.json
            backend/package-lock.json

      - name: FE Install Dependencies
        run: npm ci
        # working-directory: library-app # УДАЛЕНО: Выполняем в корне

      - name: FE Build
        run: npm run build --if-present
        # working-directory: library-app # УДАЛЕНО: Выполняем в корне

      - name: FE Test
        run: npm test
        # working-directory: library-app # УДАЛЕНО: Выполняем в корне
        env:
          CI: true

      - name: BE Install Dependencies
        run: npm ci
        working-directory: backend # ОСТАВЛЕНО: Переходим в папку backend

      # Закомментированный шаг для тестов бэкенда
      # - name: BE Test
      #   run: npm test
      #   working-directory: backend
      #   env:
      #     CI: true
